### PR TITLE
all: add ArcSegments to create segments along an elliptical arc

### PR DESCRIPTION
**Pull request by sbinet**
Signed-off-by: Sebastien Binet <binet@cern.ch>

### CODE REVIEW

**Comment by sbinet** [comment]
I had to also include a chunk of the `f32.Affine2D` code along the way...

also: I am a bit out of steam to rework the code to directly generate the cubic Bézier segments instead of the quadratic ones from the original paper...

https://modules.raku.org/dist/PDF::Document:cpan:TBROWDER/resources/elliptical-arc.pdf

**Comment by andybalholm** [comment]
I already have code to produce a single-segment cubic approximation of a *circular* arc, starting on line 172 of stroke.go (for round joins). So it should be possible to break the arc into small enough segments (I would recommend 1/8 circle), choose the control points as specified there, and apply the transformation to convert it to an elliptical arc.

**Comment by sbinet** [comment]
PTAL

**Comment by andybalholm** [comment]
`k` shouldn't be based on the total angle, but on the angle per cubic segment (`angle / float32(segs)`). 

The next step is probably to write a test that generates some arcs, iterates along their lenght, and verifies that for each point the sum of the distances from the foci is close enough to correct.

**Comment by andybalholm** [comment]
I don't think how you're finding the control points is going to work. 

My inclination would be to solve the simpler case of circular arcs first, and wrap that in a function that applies a transformation matrix to convert the circular arc into an elliptical one.

**Comment by sbinet** [comment]
obviously, I don't have the adequate bandwidth for this.
sorry.

**Comment by andybalholm** [comment]
I finally found time to implement the design I had been thinking of: https://github.com/andybalholm/stroke/pull/2

PTAL

**Pull request closed without merging**
